name: cli-release
# Releases the Devbox CLI

concurrency: cli-release

on:
  # Build/Release on demand
  workflow_dispatch:
    inputs:
      update_nightly:
        description: "Update nightly?"
        required: false
        default: false
        type: boolean
  schedule:
    - cron: "0 0 * * *" # Nightly
  push:
    tags:
      - "*" # Tags that trigger a new release version

permissions:
  contents: write
  pull-requests: read
  id-token: write # Needed for aws-actions/configure-aws-credentials@v1

env:
  NIGHTLY_TAG: 0.0.0-nightly

jobs:
  tests:
    uses: ./.github/workflows/cli-tests.yaml
    with:
      run-mac-tests: true

  nightly:
    runs-on: ubuntu-latest
    environment: release
    # needs: tests
    if: ${{ inputs.update_nightly || github.event.schedule }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed by goreleaser to browse history.
      - name: Set nightly tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.NIGHTLY_TAG }}
          tag_prefix: ""
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: true
      - name: Build snapshot with goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-publish --skip-announce --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEMETRY_KEY: ${{ secrets.TELEMETRY_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: development
          # TODO: Add hash or date.
          version:  ${{ env.NIGHTLY_TAG }}
      - name: Publish snapshot release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          fail_on_unmatched_files: true
          tag_name: ${{ env.NIGHTLY_TAG }}
          name: nightly
          files: |
            dist/checksums.txt
            dist/*.tar.gz

  release:
    runs-on: ubuntu-latest
    environment: release
    needs: tests
    # Only release when there's a tag for the release.
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed by goreleaser to browse history.
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: false
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ github.ref }}
      - name: Release with goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
          DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEMETRY_KEY: ${{ secrets.TELEMETRY_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
